minCheck: 10
maxCheck: auto
vFov: 35.0
hFov: 65.0
#Will show combat tagged players, this is nice if you're hiding invis players
showCombatTagged: true
#the duration of blinding in minutes
#this is amplified by 1 minute for each offense and applies nausea and blindness for the duration
blindDuration: 3
#Max degree/second turning speed to flag for bypass
#Default of 500 is pretty hard to flag even if you're spinning really fast
maxSpin: 500
#The maximum number of flags per time
maxFlags: 100
#The time in seconds between flag number checks
flagTime: 60
#calculate and show timing data (really just for dev purposes)
timing: false
#Whether or not to run a synthetic load test, pretty much exclusively for testing purposes.
#Make sure your minCheck is less than 10 and maxCheck is greater than 100 (or have a view distance of at least 6 with auto) to get the best indication of performance under load
#This synthetic test is much more intensive than you will realistically ever see. I suggest turning timings on as well if you use this to actually have an idea of how it's doing
loadtest: false
maxLogoutTime: 600000
#currently in testing, not recommended for live
hideEntities: false
suppresslogging: true
selfieDelay: 60000
